### ISSUE TITLE
Error occurred when I run the eval_cityscapes_server.lua.

### ISSUE THREAD

**Issue by wangq95** [Eromera/erfnet#11]
Hi,
When I try to run the eval_cityscapes_server.lua to test on the VAL subset of Cityscapes database with(CUDA8.0.61, CuDNN5.1.1 and Torch7.0), the error occurred:

THCudaCheck FAIL file=/home/ted/dl_framework/torch/extra/cunn/lib/THCUNN/generic/SpatialDilatedMaxPooling.cu line=152 error=8 : invalid device function
/home/ted/dl_framework/torch/install/bin/luajit: ...l_framework/torch/install/share/lua/5.1/nn/Container.lua:67: 
In 1 module of nn.Sequential:
In 1 module of nn.Sequential:
In 2 module of nn.ConcatTable:
In 1 module of nn.Sequential:
...ted/dl_framework/torch/install/share/lua/5.1/nn/THNN.lua:110: cuda runtime error (8) : invalid device function at /home/ted/dl_framework/torch/extra/cunn/lib/THCUNN/generic/SpatialDilatedMaxPooling.cu:152
stack traceback:
	[C]: in function 'v'
	...ted/dl_framework/torch/install/share/lua/5.1/nn/THNN.lua:110: in function 'SpatialMaxPooling_updateOutput'
	...ork/torch/install/share/lua/5.1/nn/SpatialMaxPooling.lua:47: in function <...ork/torch/install/share/lua/5.1/nn/SpatialMaxPooling.lua:31>
	[C]: in function 'xpcall'
	...l_framework/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
	..._framework/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function <..._framework/torch/install/share/lua/5.1/nn/Sequential.lua:41>
	[C]: in function 'xpcall'
	...l_framework/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
	...framework/torch/install/share/lua/5.1/nn/ConcatTable.lua:11: in function <...framework/torch/install/share/lua/5.1/nn/ConcatTable.lua:9>
	[C]: in function 'xpcall'
	...l_framework/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
	..._framework/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function <..._framework/torch/install/share/lua/5.1/nn/Sequential.lua:41>
	[C]: in function 'xpcall'
	...l_framework/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
	..._framework/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
	eval_cityscapes_server.lua:83: in main chunk
	[C]: in function 'dofile'
	...work/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405d50

        How to solve this problem? Thanks, best regards.

**Comment by Eromera** [comment]
Hi, can you make sure that your gpu is operating correctly and you are calling the right CUDA device?
