### ISSUE TITLE
About these model's prototxts

### ISSUE THREAD

**Issue by sunpeng1996** [Eromera/erfnet#4]
hi,all:
  I want to reproduce these two experiments in cityscapes. Could you provide the model prototxt in caffe for me?

**Comment by Eromera** [comment]
Hi! Currently we only have code in PyTorch or Torch so we do not have the prototxt for the network definition as in Caffe. You could try to generate the prototxt by looking at the PyTorch/Torch definitions, either by creating them by hand (all used layers should exist in mainstream Caffe) or by using one of those converters that some developers created (e.g. pytorch2caffe)
