### ISSUE TITLE
cpu load gpu trained model eval error

### ISSUE THREAD

**Issue by guanfuchen** [Eromera/erfnet#7]
![image](https://user-images.githubusercontent.com/22321977/34206799-f95db570-e5c2-11e7-9dd0-c659149f911a.png)
I use cpu to eval the trained model but the result is wrong, I check the model does not load the weights correctly, but I succeed eval the result in cpu mode when change the code like that.

**Comment by Eromera** [comment]
Thank you! I'll modify the code as soon as I can with this addition. The code was fully tested in GPU so I did not debug CPU appropiately and there should be a couple of bugs like this that involve loading weights in a way that is only possible in GPU. My intention is to adapt the code to be more general so once I am able to test it I will modify the repository code. Thanks!
