### ISSUE TITLE
Is the inference time of the model related to the parameter quantity of the model?

### ISSUE THREAD

**Issue by InstantWindy** [Eromera/erfnet#8]
How do you calculate the GFLOPS of a model? The less the parameter quantity of the model, the shorter the inference time of the model?

**Comment by Eromera** [comment]
Hi, yes it is related. You can calculate both parameter amount and GFLOPS using  [this repository](https://github.com/e-lab/Torch7-profiling).

**Comment by wangq95** [comment]
Hi,
I was confused about the inference time of ErfNet, when I use the script 'eval_forwardTime.py' , I got only 10fps with input size(1024*2048) on 1080ti, but the reported speed is about 50fps, so which is more credible? And why should add 0.0257 here? Best regards.

if i!=0:    #first run always takes some time for setup
       fwt = time.time() - start_time + 0.0257

**Comment by Eromera** [comment]
Hi, the forward time in the paper is obtained using 1024x512. I don't know where that line with the 0.0257 is.

**Comment by InstantWindy** [comment]
@Eromera  ,Hi! When my convolution kernel value is only 1 and -1 or when my input value is only 1 and -1, will the network run faster? Thanks!

**Comment by Eromera** [comment]
Hi, it should be the same since you are computing a conv operation using a float. You can have a look at binary convolutions (XNOR net and so on).

**Comment by InstantWindy** [comment]
Hey, I read XNOR net and found that XNOR net binarizes weights and inputs with values of 1 and - 1.

**Comment by Eromera** [comment]
@InstantWindy Yes I know about XNOR and I've tried it myself. In my case performance was far from being the same as the 16/32 bit float model, but maybe there's another way to quantize weights further
